### PR TITLE
Reimplement Platformio commands in Lua to enable arguments completion

### PR DESCRIPTION
**Pull request by dhupee**
As per my issue in #9 I implemented adding argument by reimplementing platformio.vim in Lua, though I didn't remove it, and instead rename in as .vim.bak just in case.

It doesn't need other plugins as dependencies as its just reimplement existing feature.

Need other's check to be merge in upstream

thx, dhupee

### CODE REVIEW

**Comment by anurag3301** [comment]
Great work, before I merge it i'd like to mention few stuff, see if you figure them out, else I'll check it out

1. Piomon takes baud rate as argument, it would be great to have a list of common baud rates as completion
2. Try squashing some commits, remove some mistaken commits or combine related commits

**Comment by dhupee** [comment]
I'll do the Second, the first so its like the argument option like in Piorun?

**Comment by dhupee** [comment]
done the squashing, although for the Baud Rate options I will do "uploadfs" also since #11 is there

**Comment by dhupee** [comment]
i'll reopen once its done

**Pull request closed without merging**
